Repository fac-23/microblogging-oli-orian-miah, pull requests merged in 2022-01, with the labels that each got.

#12 add test for moo-post
  cypress/integration/tests.js
Labels: quality assurance

#20 Testing delete post and link CSS
  cypress/integration/tests.js
  public/style.css
  scrap.html
  server.js
Labels: quality assurance, UI/UX

#21 Tests and server code for 404 page
  cypress/integration/tests.js
  public/404.css
  server.js
Labels: enhancement, quality assurance

#22 Cow styling
  public/moonet-logo.png
  public/style.css
  scrap.html
  server.js
Labels: UI/UX

#24 Finishing touches
  .DS_Store
  cypress/integration/tests.js
  public/404.css
  public/sadCow.jpg
  server.js
Labels: enhancement, UI/UX

#25 Fix date bug
  server.js
Labels: bug

#28 Add form styles on user posts
  public/style.css
Labels: UI/UX
